/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import models.Product;
import servicios.AdminServices;
import servicios.ProductServices;

/**
 * @author juanruiz
 * @author mafemartinez
 * @author angiecgomez
 */
public class JFrameMain extends javax.swing.JFrame {

    AdminServices adminServices = new AdminServices();
    ProductServices productServices = new ProductServices();
    List<Product> productList = new ArrayList<Product>();

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        Inicio = new javax.swing.JTabbedPane();
        Productos = new javax.swing.JPanel();
        jPanelListarP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnListarP = new javax.swing.JButton();
        jPanelRegistrarP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFCodigoP = new javax.swing.JTextField();
        jTFNombreP = new javax.swing.JTextField();
        jTFValorInicialP = new javax.swing.JTextField();
        btnRegistrarP = new javax.swing.JButton();
        Subastas = new javax.swing.JPanel();
        jPanelListarS = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnListarS = new javax.swing.JButton();
        jPanelCrearS = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFCodP = new javax.swing.JTextField();
        btnSubastar = new javax.swing.JButton();
        btnCerrarS = new javax.swing.JButton();
        CerrarSesión = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Inicio.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N

        jPanelListarP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listar Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 0, 14))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Estado", "Valor Inicial"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jScrollPane1.setViewportView(jScrollPane2);

        btnListarP.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnListarP.setText("Listar");
        btnListarP.setActionCommand("");

        btnListarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListarPLayout = new javax.swing.GroupLayout(jPanelListarP);
        jPanelListarP.setLayout(jPanelListarPLayout);
        jPanelListarPLayout.setHorizontalGroup(
            jPanelListarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarPLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListarPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListarP, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        jPanelListarPLayout.setVerticalGroup(
            jPanelListarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarPLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnListarP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnListarP.getAccessibleContext().setAccessibleName("Listar");

        jPanelRegistrarP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 0, 14))); // NOI18N

        jLabel1.setText("Código");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Valor Inicial:");

        jTFCodigoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodigoPActionPerformed(evt);
            }
        });

        btnRegistrarP.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnRegistrarP.setText("Registrar");

        btnRegistrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistrarPLayout = new javax.swing.GroupLayout(jPanelRegistrarP);
        jPanelRegistrarP.setLayout(jPanelRegistrarPLayout);
        jPanelRegistrarPLayout.setHorizontalGroup(
            jPanelRegistrarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarPLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelRegistrarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(jPanelRegistrarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTFNombreP, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addComponent(jTFCodigoP)
                    .addComponent(jTFValorInicialP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistrarPLayout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addComponent(btnRegistrarP, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        jPanelRegistrarPLayout.setVerticalGroup(
            jPanelRegistrarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarPLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelRegistrarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistrarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegistrarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFValorInicialP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnRegistrarP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ProductosLayout = new javax.swing.GroupLayout(Productos);
        Productos.setLayout(ProductosLayout);
        ProductosLayout.setHorizontalGroup(
            ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductosLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addGroup(ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRegistrarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelListarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        ProductosLayout.setVerticalGroup(
            ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanelRegistrarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelListarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelRegistrarP.getAccessibleContext().setAccessibleParent(jPanelRegistrarP);

        Inicio.addTab("Productos", Productos);

        jPanelListarS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listar Subastas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 0, 14))); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Estado", "Valor Inicial"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jScrollPane3.setViewportView(jScrollPane4);

        btnListarS.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnListarS.setText("Listar");
        btnListarS.setActionCommand("");

        btnListarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListarSLayout = new javax.swing.GroupLayout(jPanelListarS);
        jPanelListarS.setLayout(jPanelListarSLayout);
        jPanelListarSLayout.setHorizontalGroup(
            jPanelListarSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarSLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListarSLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListarS, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        jPanelListarSLayout.setVerticalGroup(
            jPanelListarSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarSLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnListarS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelCrearS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear - Cerrar Subasta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 0, 14))); // NOI18N

        jLabel4.setText("Por favor, ingrese el código del producto que desea subastar o en su defecto cerrar la subasta.");

        jLabel5.setText("Código:");

        btnSubastar.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnSubastar.setText("Subastar");

        btnSubastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubastarActionPerformed(evt);
            }
        });

        btnCerrarS.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnCerrarS.setText("Cerrar Subasta");

        javax.swing.GroupLayout jPanelCrearSLayout = new javax.swing.GroupLayout(jPanelCrearS);
        jPanelCrearS.setLayout(jPanelCrearSLayout);
        jPanelCrearSLayout.setHorizontalGroup(
            jPanelCrearSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearSLayout.createSequentialGroup()
                .addGroup(jPanelCrearSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCrearSLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelCrearSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanelCrearSLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jTFCodP, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelCrearSLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnSubastar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrarS)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCrearSLayout.setVerticalGroup(
            jPanelCrearSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearSLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCrearSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFCodP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrearSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubastar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SubastasLayout = new javax.swing.GroupLayout(Subastas);
        Subastas.setLayout(SubastasLayout);
        SubastasLayout.setHorizontalGroup(
            SubastasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubastasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(SubastasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelListarS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCrearS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        SubastasLayout.setVerticalGroup(
            SubastasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubastasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanelCrearS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanelListarS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanelCrearS.getAccessibleContext().setAccessibleName("Crear - Cerrar Subasta");

        Inicio.addTab("Subastas", Subastas);

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel6.setText("¡Hasta Pronto :*!");

        javax.swing.GroupLayout CerrarSesiónLayout = new javax.swing.GroupLayout(CerrarSesión);
        CerrarSesión.setLayout(CerrarSesiónLayout);
        CerrarSesiónLayout.setHorizontalGroup(
            CerrarSesiónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CerrarSesiónLayout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(261, 261, 261))
        );
        CerrarSesiónLayout.setVerticalGroup(
            CerrarSesiónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CerrarSesiónLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel6)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        Inicio.addTab("Cerrar Sesión", CerrarSesión);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Inicio)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Inicio)
        );

        Inicio.getAccessibleContext().setAccessibleName("Inicio");

        getContentPane().add(jPanelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFCodigoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodigoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCodigoPActionPerformed


    private void btnRegistrarPActionPerformed(java.awt.event.ActionEvent evt){

        if(!jTFNombreP.getText().isEmpty() && !jTFCodigoP.getText().isEmpty() && !jTFValorInicialP.getText().isEmpty()){
            String name = jTFNombreP.getText();
            int cod = Integer.parseInt(jTFCodigoP.getText());
            int price = Integer.parseInt(jTFValorInicialP.getText());

            Product newProduct = new Product(cod, name, "En stock", price);

            Product response = productServices.registerProduct(newProduct);

            if(response != null){
                JOptionPane.showMessageDialog(this, "El nuevo producto se ha regitrado");
            }

        }else{
            JOptionPane.showMessageDialog(this, "Ingrese todos los campos pls >:c");
        }
    }

    private void btnListarPActionPerformed(java.awt.event.ActionEvent evt){

        productList = productServices.listAllProducts();

        Object[] data = new Object[productList.size()];

        for(int i = 0; i < productList.size(); i++){
            data[i] = productList.get(i);
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                data
            },
            new String [] {
                "Código", "Noombre", "Estado", "Valor Inicial"
            }
        ));
    }

    private void btnListarSActionPerformed(java.awt.event.ActionEvent evt){

        productList = productServices.listAllProducts();

        Object[] data = new Object[productList.size()];

        for(int i = 0; i < productList.size(); i++){
            data[i] = productList.get(i);
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                data
            },
            new String [] {
                "Código", "Nombre", "Estado", "Valor Inicial"
            }
        ));
    }

    private void btnSubastarActionPerformed(java.awt.event.ActionEvent evt){
        int id = Integer.parseInt(jTFCodP.getText());

        Product product = productServices.findProductByID(id);
        Product auctionProduct = productServices.getAuctionProduct();

        if(product != null){
            if(auctionProduct != null){
                productServices.updateAuctionProduct(auctionProduct.getCod(), "Vendido", auctionProduct);
                Product newAuctionProduct = productServices.updateAuctionProduct(id, "En Subasta", product);
                if(newAuctionProduct != null){
                    JOptionPane.showMessageDialog(this, "Actualización Exitosa");
                }
            }else{
                Product newAuctionProduct = productServices.updateAuctionProduct(id, "En Subasta", product);
                if(newAuctionProduct != null){
                    JOptionPane.showMessageDialog(this, "Actualización Exitosa");
                }
            }

        }else{
            JOptionPane.showMessageDialog(this, "Ingrese todos los campos porfi >:c");
        }


    }

    




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CerrarSesión;
    private javax.swing.JTabbedPane Inicio;
    private javax.swing.JPanel Productos;
    private javax.swing.JPanel Subastas;
    private javax.swing.JButton btnCerrarS;
    private javax.swing.JButton btnListarP;
    private javax.swing.JButton btnListarS;
    private javax.swing.JButton btnRegistrarP;
    private javax.swing.JButton btnSubastar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelCrearS;
    private javax.swing.JPanel jPanelListarP;
    private javax.swing.JPanel jPanelListarS;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelRegistrarP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTFCodP;
    private javax.swing.JTextField jTFCodigoP;
    private javax.swing.JTextField jTFNombreP;
    private javax.swing.JTextField jTFValorInicialP;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
